version: '3'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/tpaga_test
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:11.7
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dblogs:/var/log/postgresql

volumes:
  dbdata:
    driver: local
  dblogs:
    driver: local