version: '3'

services:  
  postgres:
    image: postgres:11.7
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dblogs:/var/log/postgresql
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5433"

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - 'redis:/data'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/tpaga_test
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

volumes:
  dbdata:
    driver: local
  dblogs:
    driver: local
  redis:
    driver: local