default: &default
  adapter: postgresql
  encoding: utf8
  host: postgres
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: tpaga_test_development

test:
  <<: *default
  database: tpaga_test

production:
  <<: *default
  url: <%= ENV['DB_URL']%>
